appid: "8b78ee8d"
api_secret: "MjMxZDVhNzE1OGE2MmU4MmNlNzEwNjYx"
api_key: "deb208978c5ae4773f02b1f035a0f1b8"

#用于配置大模型版本，默认“general/generalv2”
# domain: "general"   # v1.5版本
domain: "generalv2"    # v2.0版本

#云端环境的服务地址
# Spark_url: "ws://spark-api.xf-yun.com/v1.1/chat"  # v1.5环境的地址
Spark_url: "ws://spark-api.xf-yun.com/v2.1/chat"  # v2.0环境的地址

# 本地参数
iat_pcm: "data/iat.pcm"
tts_pcm: "data/tts.pcm"